# Generated by Django 4.2.30 on 2026-06-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='content',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
