# Generated by Django 4.2.30 on 2026-06-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_topic_generationjob_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='generationjob',
            name='audiences',
            field=models.ManyToManyField(blank=True, to='contents.audience'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='goals',
            field=models.ManyToManyField(blank=True, to='contents.goal'),
        ),
    ]
