# Generated by Django 4.2.30 on 2026-06-08 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_audience_goal_generationjob_audiences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.audience'),
        ),
        migrations.AddField(
            model_name='content',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.goal'),
        ),
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.topic'),
        ),
    ]
