# Generated by Django 4.2.30 on 2026-06-08 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_appsettings_blockedkeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system_prompt', models.TextField()),
                ('user_prompt_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='appsettings',
            name='model_name',
            field=models.CharField(default='gpt-4.1-mini', max_length=100),
        ),
        migrations.AddField(
            model_name='content',
            name='prompt_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.prompttemplate'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='prompt_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.prompttemplate'),
        ),
    ]
