# Generated by Django 4.2.30 on 2026-06-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_prompttemplate_appsettings_model_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('prompt_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='rules',
            field=models.ManyToManyField(blank=True, to='contents.contentrule'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='rules',
            field=models.ManyToManyField(blank=True, to='contents.contentrule'),
        ),
    ]
