# Generated by Django 4.2.30 on 2026-06-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_language_content_language_generationjob_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
