# Generated by Django 4.2.30 on 2026-06-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_generationjob_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='should_stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=20),
        ),
    ]
