# Generated by Django 4.2.30 on 2026-06-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_generationjob_should_stop_alter_generationjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJobLanguageDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_distributions', to='contents.generationjob')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.language')),
            ],
            options={
                'unique_together': {('job', 'language')},
            },
        ),
    ]
