# Generated by Django 4.2.30 on 2026-06-13 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_generationjoblanguagedistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJobTopicDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_distributions', to='contents.generationjob')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.topic')),
            ],
            options={
                'unique_together': {('job', 'topic')},
            },
        ),
    ]
