# Generated by Django 4.2.30 on 2026-06-13 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_generationjobtopicdistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJobAudienceDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(default=1)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.audience')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_distributions', to='contents.generationjob')),
            ],
            options={
                'unique_together': {('job', 'audience')},
            },
        ),
    ]
