# Generated by Django 4.2.30 on 2026-06-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_generationjobaudiencedistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='current_step',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GenerationJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='contents.generationjob')),
            ],
        ),
    ]
