# Generated by Django 4.2.30 on 2026-06-13 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0016_generationjob_current_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJobGoalDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(default=1)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.goal')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_distributions', to='contents.generationjob')),
            ],
            options={
                'unique_together': {('job', 'goal')},
            },
        ),
    ]
