# Generated by Django 4.2.30 on 2026-06-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0017_generationjobgoaldistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='api_secret_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
