# Generated by Django 4.2.30 on 2026-06-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0018_appsettings_api_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='auto_generate_api_key',
            field=models.BooleanField(default=True),
        ),
    ]
