# Generated by Django 4.2.30 on 2026-06-13 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0019_appsettings_auto_generate_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='default_generation_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.generationjob'),
        ),
    ]
