# Generated by Django 4.2.30 on 2026-06-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0020_appsettings_default_generation_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='prompt_templates',
            field=models.ManyToManyField(blank=True, help_text='If selected, one active template will be chosen by weight for each generated content.', related_name='weighted_generation_jobs', to='contents.prompttemplate'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Higher weight means this template is selected more often.'),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='prompt_template',
            field=models.ForeignKey(blank=True, help_text='Fallback prompt template. Used when weighted prompt templates are empty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_generation_jobs', to='contents.prompttemplate'),
        ),
    ]
