# Generated by Django 4.2.30 on 2026-06-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0021_generationjob_prompt_templates_prompttemplate_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Higher weight means this audience is selected more often.'),
        ),
        migrations.AddField(
            model_name='contentrule',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Higher weight means this rule is selected more often.'),
        ),
        migrations.AddField(
            model_name='goal',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Higher weight means this goal is selected more often.'),
        ),
        migrations.AddField(
            model_name='language',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Higher weight means this language is selected more often.'),
        ),
        migrations.AddField(
            model_name='topic',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Higher weight means this topic is selected more often.'),
        ),
    ]
