# Generated by Django 4.2.30 on 2026-06-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0022_audience_weight_contentrule_weight_goal_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='use_all_audiences',
            field=models.BooleanField(default=False, help_text='Use all active audiences instead of selected audiences.'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='use_all_goals',
            field=models.BooleanField(default=False, help_text='Use all active goals instead of selected goals.'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='use_all_languages',
            field=models.BooleanField(default=False, help_text='Use all active languages instead of selected languages.'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='use_all_prompt_templates',
            field=models.BooleanField(default=False, help_text='Use all active prompt templates instead of selected prompt templates.'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='use_all_rules',
            field=models.BooleanField(default=False, help_text='Use all active content rules instead of selected rules.'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='use_all_topics',
            field=models.BooleanField(default=False, help_text='Use all active topics instead of selected topics.'),
        ),
    ]
