# Generated by Django 4.2.30 on 2026-06-22 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0023_generationjob_use_all_audiences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='auto_daily_generation_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic daily content generation.'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='daily_generation_count',
            field=models.PositiveIntegerField(default=10, help_text='How many contents should be generated each day.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='daily_generation_delay_seconds',
            field=models.FloatField(default=1.0, help_text='Delay between each generated content in the daily job.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='daily_generation_hour',
            field=models.PositiveSmallIntegerField(default=2, help_text='Daily generation hour in server time. Example: 2 means 02:00.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='daily_generation_minute',
            field=models.PositiveSmallIntegerField(default=0, help_text='Daily generation minute in server time.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='last_daily_generation_date',
            field=models.DateField(blank=True, help_text='Last date when the automatic daily generation ran.', null=True),
        ),
    ]
