# Generated by Django 4.2.30 on 2026-06-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0024_appsettings_auto_daily_generation_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='api_secret_key',
            field=models.CharField(blank=True, default='', help_text='Generated automatically. Leave empty only when External API access is disabled.', max_length=255),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='auto_generate_api_key',
            field=models.BooleanField(default=True, help_text='When enabled, an API key will be generated automatically if missing.'),
        ),
    ]
