# Generated by Django 4.2.30 on 2026-07-04 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0025_alter_appsettings_api_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='auto_daily_generation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='auto_generate_api_key',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='daily_generation_count',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='daily_generation_delay_seconds',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='daily_generation_hour',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='daily_generation_minute',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='last_daily_generation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='use_all_audiences',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='use_all_goals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='use_all_languages',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='use_all_prompt_templates',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='use_all_rules',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='use_all_topics',
            field=models.BooleanField(default=False),
        ),
    ]
