# Generated by Django 4.2.30 on 2026-07-04 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0026_content_content_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='auto_refill_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='auto_refill_item_count',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='auto_refill_skip_threshold',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
