# Generated by Django 4.2.30 on 2026-07-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0027_appsettings_auto_refill_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('topic', 'Topic'), ('audience', 'Audience'), ('goal', 'Goal')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('skip_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('blocked_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('quality_score', models.FloatField(default=100)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('item_type', 'item_id')},
            },
        ),
    ]
