# Generated by Django 4.2.30 on 2026-07-05 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0028_datasetperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('topic', 'Topic'), ('audience', 'Audience'), ('goal', 'Goal')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('success', 'Success'), ('duplicate', 'Duplicate'), ('blocked', 'Blocked'), ('error', 'Error'), ('skip', 'Skip')], max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.content')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.generationjob')),
            ],
            options={
                'indexes': [models.Index(fields=['item_type', 'item_id'], name='contents_da_item_ty_cb28c4_idx'), models.Index(fields=['event_type'], name='contents_da_event_t_dfa849_idx'), models.Index(fields=['created_at'], name='contents_da_created_f68cec_idx')],
            },
        ),
    ]
