# Generated by Django 4.2.30 on 2026-07-05 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0029_datasetevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='openai', max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('purpose', models.CharField(choices=[('content_generation', 'Content Generation'), ('dataset_generation', 'Dataset Generation'), ('intelligence', 'Intelligence'), ('title_generation', 'Title Generation'), ('other', 'Other')], default='content_generation', max_length=50)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider'], name='contents_ai_provide_b24a79_idx'), models.Index(fields=['purpose'], name='contents_ai_purpose_8cfae7_idx'), models.Index(fields=['created_at'], name='contents_ai_created_a212e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='GenerationPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('skip_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('blocked_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('quality_score', models.FloatField(default=100)),
                ('confidence', models.FloatField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.audience')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.goal')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.language')),
                ('prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.prompttemplate')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.topic')),
            ],
            options={
                'indexes': [models.Index(fields=['topic', 'audience', 'goal'], name='contents_ge_topic_i_261f23_idx'), models.Index(fields=['language', 'prompt_template'], name='contents_ge_languag_c27878_idx'), models.Index(fields=['quality_score'], name='contents_ge_quality_3675ff_idx'), models.Index(fields=['confidence'], name='contents_ge_confide_e855d0_idx'), models.Index(fields=['updated_at'], name='contents_ge_updated_9c250b_idx')],
            },
        ),
    ]
