# Generated by Django 4.2.30 on 2026-07-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0030_aiusagelog_generationpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
