# Generated by Django 4.2.30 on 2026-07-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0031_generationjob_max_retries_generationjob_retry_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generationjoblog',
            options={'verbose_name': 'System Settings', 'verbose_name_plural': 'System Settings'},
        ),
    ]
