# Generated by Django 4.2.30 on 2026-07-13 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0032_alter_generationjoblog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(help_text='Stable identifier used for logs and integrations, for example: panel-a.', max_length=100, unique=True)),
                ('api_key', models.CharField(blank=True, db_index=True, help_text='Generated automatically when left empty.', max_length=255, unique=True)),
                ('callback_url', models.URLField(blank=True, default='', help_text='Optional destination URL for future push-based exports.')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('remote_id', models.CharField(blank=True, default='', help_text='Optional content ID returned by the destination panel.', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_exports', to='contents.externalclient')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='contents.content')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='contents_co_client__da286f_idx'), models.Index(fields=['content', 'status'], name='contents_co_content_474804_idx'), models.Index(fields=['exported_at'], name='contents_co_exporte_f3bcd1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contentexport',
            constraint=models.UniqueConstraint(fields=('content', 'client'), name='unique_content_export_per_client'),
        ),
    ]
