# Generated by Django 4.2.30 on 2026-07-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0033_externalclient_contentexport_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contentexport',
            name='unique_content_export_per_client',
        ),
        migrations.AddField(
            model_name='contentexport',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Snapshot of the content hash at export time. A changed hash is treated as a new content version.', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='contentexport',
            constraint=models.UniqueConstraint(fields=('content', 'client', 'content_hash'), name='unique_content_version_export_per_client'),
        ),
    ]
