# Generated by Django 4.2.30 on 2026-07-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0034_remove_contentexport_unique_content_export_per_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='external_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='contents.externalclient'),
        ),
    ]
