# Generated by Django 4.2.30 on 2026-07-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0035_generationjob_external_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalclient',
            name='api_key_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='externalclient',
            name='api_key_prefix',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='externalclient',
            name='api_key',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Legacy plaintext API key. New keys are stored hashed.', max_length=255, null=True, unique=True),
        ),
    ]
