# Generated by Django 4.2.30 on 2026-07-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0036_externalclient_api_key_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('destination_url', models.URLField(max_length=2048)),
                ('purpose', models.CharField(default='callback', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_deliveries', to='contents.externalclient')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='contents.content')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='contents_co_client__56bcf7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contentdelivery',
            constraint=models.UniqueConstraint(fields=('client', 'content', 'content_hash', 'purpose'), name='unique_content_delivery_per_client_version'),
        ),
    ]
