# Generated by Django 4.2.30 on 2026-07-15 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0037_contentdelivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=255)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('resource_type', models.CharField(blank=True, default='', max_length=50)),
                ('resource_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='contents.externalclient')),
            ],
        ),
        migrations.AddConstraint(
            model_name='apiidempotencyrecord',
            constraint=models.UniqueConstraint(fields=('client', 'operation', 'key'), name='unique_api_idempotency_key_per_client_operation'),
        ),
    ]
