# Generated by Django 4.2.30 on 2026-07-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0038_apiidempotencyrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalclient',
            name='daily_export_item_quota',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalclient',
            name='limits_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='externalclient',
            name='max_active_generation_jobs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalclient',
            name='max_generation_content_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalclient',
            name='requests_per_minute',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
