# Generated by Django 4.2.30 on 2026-07-15 17:05

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('contents', '0039_externalclient_daily_export_item_quota_and_more'),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        django.contrib.postgres.operations.AddIndexConcurrently(
            model_name='content',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='content_title_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
        django.contrib.postgres.operations.AddIndexConcurrently(
            model_name='content',
            index=django.contrib.postgres.indexes.GinIndex(fields=['prompt'], name='content_prompt_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
        django.contrib.postgres.operations.AddIndexConcurrently(
            model_name='content',
            index=django.contrib.postgres.indexes.GinIndex(fields=['generated_content'], name='content_body_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
