# Generated by Django 4.2.30 on 2026-07-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0040_content_content_title_trgm_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='generation_attempt_multiplier',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='generation_max_runtime_seconds',
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='generation_minimum_attempts',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='attempted_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='duplicate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='empty_output_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='failed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='max_attempts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
