# Generated by Django 4.2.30 on 2026-07-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0041_appsettings_generation_attempt_multiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('standard', 'Standard Content'), ('email_reply', 'Email Reply')], db_index=True, default='standard', max_length=30),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='generation_type',
            field=models.CharField(choices=[('standard', 'Standard Content'), ('email_reply', 'Email Reply')], db_index=True, default='standard', max_length=30),
        ),
    ]
