# Generated by Django 4.2.30 on 2026-07-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0042_content_content_type_generationjob_generation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='api_secret_key',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='auto_generate_api_key',
        ),
    ]
