# Generated by Django 4.2.30 on 2026-07-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0043_remove_appsettings_api_secret_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReply',
            fields=[
            ],
            options={
                'verbose_name': 'Email Reply',
                'verbose_name_plural': 'Email Replies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contents.content',),
        ),
    ]
