# Generated by Django 4.2.30 on 2026-07-21 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0044_emailreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='auto_daily_reply_generation_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic daily email reply generation.'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='daily_reply_generation_count',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='daily_reply_generation_delay_seconds',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='daily_reply_generation_hour',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='daily_reply_generation_minute',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='last_daily_reply_generation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
