# Generated by Django 4.2.30 on 2026-07-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0045_appsettings_auto_daily_reply_generation_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Unique identifier, for example: language, topic, tone.', unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dataset Category',
                'verbose_name_plural': 'Dataset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GenerationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Unique identifier, for example: standard, reply, greeting.', unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Generation Type',
                'verbose_name_plural': 'Generation Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GenerationTypeDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('selection_order', models.PositiveSmallIntegerField(default=0, help_text='Lower values are selected first.')),
                ('weight', models.PositiveSmallIntegerField(default=100, help_text='Relative weight used when this dataset participates in generation.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_type_links', to='contents.datasetcategory')),
                ('generation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_links', to='contents.generationtype')),
            ],
            options={
                'verbose_name': 'Generation Type Dataset',
                'verbose_name_plural': 'Generation Type Datasets',
                'ordering': ['generation_type', 'selection_order', 'dataset_category'],
            },
        ),
        migrations.AddConstraint(
            model_name='generationtypedataset',
            constraint=models.UniqueConstraint(fields=('generation_type', 'dataset_category'), name='unique_generation_type_dataset'),
        ),
    ]
