# Generated by Django 4.2.30 on 2026-07-29 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0047_seed_generation_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('generated', 'Generated'), ('failed', 'Failed')], db_index=True, default='reserved', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('reserved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_fingerprints', to='contents.content')),
                ('generation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_fingerprints', to='contents.generationtype')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_fingerprints', to='contents.generationjob')),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['generation_type', 'status'], name='genfp_type_status_idx'), models.Index(fields=['status', 'reserved_at'], name='genfp_status_reserved_idx')],
            },
        ),
    ]
