# Generated by Django 4.2.30 on 2026-08-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0051_appsettings_auto_daily_greeting_generation_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
            ],
            options={
                'verbose_name': 'Greeting',
                'verbose_name_plural': 'Greetings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contents.content',),
        ),
        migrations.CreateModel(
            name='GreetingGenerationSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Greeting Settings',
                'verbose_name_plural': 'Greeting Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contents.appsettings',),
        ),
        migrations.CreateModel(
            name='ReplyGenerationSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Email Reply Settings',
                'verbose_name_plural': 'Email Reply Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contents.appsettings',),
        ),
        migrations.CreateModel(
            name='SharedGenerationSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Shared Generation Settings',
                'verbose_name_plural': 'Shared Generation Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contents.appsettings',),
        ),
        migrations.CreateModel(
            name='StandardGenerationSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Standard Generation Settings',
                'verbose_name_plural': 'Standard Generation Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contents.appsettings',),
        ),
    ]
